### ISSUE TITLE
Stuck on search animation when going back to startpage 

### ISSUE THREAD

**Issue by armoredvortex** [kholmogorov27/chevron#1] opened 2023-03-04 07:02 UTC
# How to reproduce:
- Make a Search.
- Return to startpage using the browser back buttton

# Info: 
- Browser: Mozilla Firefox 110.0.1
- OS: 6.2.1-arch1-1

# Video:
https://user-images.githubusercontent.com/66690593/222881004-a542b3a7-fcc3-45bf-97dc-c04eb1bed6b0.mp4

**Comment by kholmogorov27** [comment] 2023-03-05 08:47
I think the issue is caused by react keeping the old state for some reason or some kind of firefox caching mechanism.
I tried to solve the problem in the ff6b658 commit but I can't be sure if this bug is fixed or not because I can't reproduce the bug, even though I have the same version of firefox on Windows, so I need your confirmation. @ArmoredVortex

**Comment by armoredvortex** [comment] 2023-03-05 09:45
Nope, The issue still persists.

Edit (1): I also tried it on Chrome 110.0.5481.177 (64 bit) and have the same broken behavior.

Edit (2):For some reason Microsoft Edge 110.0.1587.63 works just fine.

**Comment by armoredvortex** [comment] 2023-03-05 10:10
Firefox and Edge Side by Side:

https://user-images.githubusercontent.com/66690593/222954140-4a9036c3-48ef-42ca-ab95-3965fd1a1836.mp4

**Comment by MiftikCZ** [comment] 2023-03-05 18:32
_for the owner here is hint how to fix it:_ after some link opens, make sure right after to close the animation and move the user to the default page

**Comment by kholmogorov27** [comment] 2023-03-06 01:41
I had to intall Arch to reproduce the bug 😅
It turned out that firefox doesn't "destroy" pages immediately and keeps them in memory for some time after user redirected away from them
The bug is fixed in the f81dd24 commit

**Closed as completed by kholmogorov27** 2023-03-06 01:41 UTC
Labels: bug
